version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}  # Паролата за root потребителя на MySQL
      MYSQL_DATABASE: mobilelele  # Името на базата данни
      MYSQL_USER: ${MYSQL_USER:-root}  # Потребителското име за MySQL
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-1122}  # Паролата за MySQL потребителя
    ports:
      - "3306:3306"  # Пренасочване на портовете за MySQL (локален порт:контейнер порт)

  mobilelele:  # Добавяме услугата за Spring приложението
    image: mobilelele:latest  # Заменете със своя образ на Spring приложението
    ports:
      - "8080:8080"  # Пренасочване на портовете за Spring приложението (локален порт:контейнер порт)
    environment:
      MYSQL_HOST: db  # Името на услугата за MySQL (това съответства на името на услугата в docker-compose)
      MYSQL_USER: ${MYSQL_USER:-root}  # Потребителското име за MySQL (същото като горе)
      MYSQL_PASS: ${MYSQL_PASSWORD:-1122}  # Паролата за MySQL потребителя (същото като горе)

      # Останалите настройки за Spring приложението
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mobilelele?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER:-root}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD:-1122}
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      SPRING_JPA_HIBERNATE_DDL-AUTO: update

      # Други настройки
      MOBILELELE_REMEMBER_ME_KEY: ${REMEMBER_ME_KEY:-secret}
      SERVER_SERVLET_SESSION_TIMEOUT: 30m
      SPRING_MAIL_HOST: smtp.example.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: ${MAIL_USER:-your-email@example.com}
      SPRING_MAIL_PASSWORD: ${YOUR_PASSWORD:-your-email-password}
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"

      #Twilio конфигурационен ключ
      TWILIO_ACCOUNT_SID: YOUR_TWILIO_ACCOUNT_SID
      TWILIO_AUTH_TOKEN: YOUR_TWILIO_AUTH_TOKEN
      TWILIO_PHONE_NUMBER: YOUR_TWILIO_PHONE_NUMBER